spring.application.name=shopping-ApiGateway
server.port=9000

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.default-zone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost

spring.cloud.gateway.routes[0].id=customer-Service
spring.cloud.gateway.routes[0].uri=lb://customer-Service
spring.cloud.gateway.routes[0].predicates[0]=Path=/customers/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.name=customer-Service
spring.cloud.gateway.routes[0].filters[0].args.fallbackuri=forward:/customerFallback

spring.cloud.gateway.routes[1].id=product-Service
spring.cloud.gateway.routes[1].uri=lb://product-Service
spring.cloud.gateway.routes[1].predicates[0]=Path=/products/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=order-Service
spring.cloud.gateway.routes[2].uri=lb://order-Service
spring.cloud.gateway.routes[2].predicates[0]=Path=/orders/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1