spring.application.name=order-Service
server.port=9003
spring.datasource.url=jdbc:mysql://localhost:3306/demorcoem
spring.datasource.username=root
spring.datasource.password=root2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

customer_service.url=http://customer_Service/v1/api/customers
product_service.url=http://product_Service/v1/api/products

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.default-zone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
